In [33]:
#Importar llibreria pandas
import pandas as pd

In [34]:
#Importar fitxers CSV (products.csv i orders.csv)
products = pd.read_csv('products.csv')
orders = pd.read_csv('orders.csv')

In [35]:
#Dades originals del DataFrame 'products'
products

   id         name       cost
0   0  screwdriver   2.981164
1   1       wrench   6.490396
2   2       hammer   2.903732
3   3       sickle   8.901570
4   4       candle   9.806495
5   5      bandsaw  10.435252

In [36]:
#Tipus de dades del DataFrame 'products'
products.dtypes

id        int64
name     object
cost    float64
dtype: object

In [37]:
#Dades originals del DataFrame 'orders'
orders

    id  customer             products
0    0         0              1 0 1 0
1    1        22    0 5 0 4 5 3 2 1 1
2    2        57                5 2 4
3    3        20            4 3 0 2 4
4    4        28          5 0 5 0 3 4
5    5        40              0 1 0 2
6    6        32    5 5 0 5 1 5 1 3 1
7    7         5              5 0 3 2
8    8        45              1 2 1 0
9    9        37            0 5 5 5 2
10  10        38        3 5 0 1 1 5 3
11  11        51            4 1 1 3 2
12  12         6              5 2 1 0
13  13        44        2 0 0 5 1 0 5
14  14        34              1 3 1 5
15  15         3            1 1 5 5 1
16  16        50    0 1 3 5 5 0 0 0 0
17  17        24      4 5 4 1 1 0 5 3
18  18        54            2 0 5 0 3
19  19        59          4 0 4 4 4 5
20  20        36                    4
21  21         8                  4 2
22  22        15    5 4 0 2 1 0 0 0 4
23  23        25                  5 5
24  24        21        2 3 0 4 4 5 4
25  25        34        1 5 0 0 3 3 0
26  26         5  2 0 4 4 5 4 2 1 2 1
27  27        34      5 5 3 3 3 0 3 4
28  28        45                  1 5
29  29        15                    2
30  30        19              5 0 4 5
31  31        41      3 2 3 4 5 1 5 2
32  32        47          5 0 3 0 1 1
33  33        48                  0 2
34  34        46          0 3 1 1 2 3
35  35        44                3 4 5
36  36        38                    5
37  37        32            5 3 1 5 4
38  38        35                  1 4
39  39        29                3 2 1
40  40        44                4 5 2
41  41        24  0 4 3 4 0 3 4 1 3 2
42  42        10    5 5 4 4 1 5 0 0 4
43  43        17      1 4 0 2 1 5 2 3
44  44         9            4 3 1 2 5
45  45        22    0 4 3 5 1 0 4 0 3
46  46        29    2 2 3 3 2 0 2 5 3
47  47         5                  2 1
48  48        44    2 3 0 5 2 2 1 1 2
49  49        58                    1

In [38]:
#Tipus de dades del DataFrame 'orders'
orders.dtypes

id           int64
customer     int64
products    object
dtype: object

In [39]:
#Crear nou DataFrame 'product_customers' amb les columnes 'id' i 'customer_ids'.
product_customers = pd.DataFrame(columns=["id", "customer_ids"])

#Copiar dades 'id' del DataFrame 'products' a 'customer_ids'
#NOTA: 'customer_ids' encara no te cap valor.
product_customers["id"] = products['id']
product_customers

   id customer_ids
0   0          NaN
1   1          NaN
2   2          NaN
3   3          NaN
4   4          NaN
5   5          NaN

In [40]:
#Tipus de dades del DataFrame 'product_customers'
product_customers.dtypes

id               int64
customer_ids    object
dtype: object

In [41]:
#Fer un split en la columna 'products' del DataFrame 'orders', generant un list dels IDs separats per espais.
orders['products'] = orders['products'].str.split()
orders

    id  customer                        products
0    0         0                    [1, 0, 1, 0]
1    1        22     [0, 5, 0, 4, 5, 3, 2, 1, 1]
2    2        57                       [5, 2, 4]
3    3        20                 [4, 3, 0, 2, 4]
4    4        28              [5, 0, 5, 0, 3, 4]
5    5        40                    [0, 1, 0, 2]
6    6        32     [5, 5, 0, 5, 1, 5, 1, 3, 1]
7    7         5                    [5, 0, 3, 2]
8    8        45                    [1, 2, 1, 0]
9    9        37                 [0, 5, 5, 5, 2]
10  10        38           [3, 5, 0, 1, 1, 5, 3]
11  11        51                 [4, 1, 1, 3, 2]
12  12         6                    [5, 2, 1, 0]
13  13        44           [2, 0, 0, 5, 1, 0, 5]
14  14        34                    [1, 3, 1, 5]
15  15         3                 [1, 1, 5, 5, 1]
16  16        50     [0, 1, 3, 5, 5, 0, 0, 0, 0]
17  17        24        [4, 5, 4, 1, 1, 0, 5, 3]
18  18        54                 [2, 0, 5, 0, 3]
19  19        59              [4, 0, 4, 4, 4, 5]
20  20        36                             [4]
21  21         8                          [4, 2]
22  22        15     [5, 4, 0, 2, 1, 0, 0, 0, 4]
23  23        25                          [5, 5]
24  24        21           [2, 3, 0, 4, 4, 5, 4]
25  25        34           [1, 5, 0, 0, 3, 3, 0]
26  26         5  [2, 0, 4, 4, 5, 4, 2, 1, 2, 1]
27  27        34        [5, 5, 3, 3, 3, 0, 3, 4]
28  28        45                          [1, 5]
29  29        15                             [2]
30  30        19                    [5, 0, 4, 5]
31  31        41        [3, 2, 3, 4, 5, 1, 5, 2]
32  32        47              [5, 0, 3, 0, 1, 1]
33  33        48                          [0, 2]
34  34        46              [0, 3, 1, 1, 2, 3]
35  35        44                       [3, 4, 5]
36  36        38                             [5]
37  37        32                 [5, 3, 1, 5, 4]
38  38        35                          [1, 4]
39  39        29                       [3, 2, 1]
40  40        44                       [4, 5, 2]
41  41        24  [0, 4, 3, 4, 0, 3, 4, 1, 3, 2]
42  42        10     [5, 5, 4, 4, 1, 5, 0, 0, 4]
43  43        17        [1, 4, 0, 2, 1, 5, 2, 3]
44  44         9                 [4, 3, 1, 2, 5]
45  45        22     [0, 4, 3, 5, 1, 0, 4, 0, 3]
46  46        29     [2, 2, 3, 3, 2, 0, 2, 5, 3]
47  47         5                          [2, 1]
48  48        44     [2, 3, 0, 5, 2, 2, 1, 1, 2]
49  49        58                             [1]

In [42]:
#For loop en el DataFrame 'product_customers'
for index_product_customer, row_product_customer in product_customers.iterrows():    
    customers_list = [] #list on guardarem els IDs dels clients interessats en el producte actual.

    #For loop en el DataFrame 'orders'
    for index_orders, row_orders in orders.iterrows():
        #Comprovar que el ID del producte esta en el llistat de productes de 'orders'
        if product_customers['id'][index_product_customer].astype('str') in orders['products'][index_orders]:
            #En cas afirmatiu, guardar ID de 'customer' que ha comprat aquell producte
            customers_list.append(orders['customer'][index_orders])

    #Guardar els IDs de 'customers_list' que han comprat el producte en la columna 'customer_ids' del DataFrame.
    #Nota: he utilitzat set() per evitar IDs repetits en un mateix producte.
    product_customers.at[index_product_customer, 'customer_ids'] = list(set(customers_list))

product_customers

   id                                       customer_ids
0   0  [0, 5, 6, 10, 15, 17, 19, 20, 21, 22, 24, 28, ...
1   1  [0, 3, 5, 6, 9, 10, 15, 17, 22, 24, 29, 32, 34...
2   2  [5, 6, 8, 9, 15, 17, 20, 21, 22, 24, 29, 37, 4...
3   3  [5, 9, 17, 20, 21, 22, 24, 28, 29, 32, 34, 38,...
4   4  [5, 8, 9, 10, 15, 17, 19, 20, 21, 22, 24, 28, ...
5   5  [3, 5, 6, 9, 10, 15, 17, 19, 21, 22, 24, 25, 2...

In [43]:
#Exportar el DataFrame en un fitxer CSV (product_customers.csv)
product_customers.to_csv("product_customers.csv", index=False)